services:
  - type: web
    name: farmanatura-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://caritoprocha:MYPJKrMM9R9che1e@cluster0.iybxy.mongodb.net/farmanatura-db?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: 3f7e8a9b5c6d4e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,http://your-frontend-domain.com
    healthCheckPath: /api/health